[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--import-mode=importlib"
testpaths = ["tests"]
pythonpath = ["."]
env_files = [".env"]
env = [
    'APP_ADMIN_ENTITLEMENTS=["iam:admin"]',
    'APP_TRUSTED_OP_LIST=[]',
    'APP_SECRETS_DIR=tests/fixtures/secrets',
]
mongodb_fixture_dir = "tests/fixtures/mongodb"

[tool.mypy]
ignore_missing_imports = true
disable_error_code = ["import-untyped"]

[tool.black]
line-length = 120
